# coding: utf-8

"""
    biodata-registry-service

     ## biodata-registry-service  Service to fetch data from Registry.  

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biodata_registry_api_client.api.data_assets_api import DataAssetsApi


class TestDataAssetsApi(unittest.TestCase):
    """DataAssetsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DataAssetsApi()

    def tearDown(self) -> None:
        pass

    def test_create_data_asset(self) -> None:
        """Test case for create_data_asset

        Create Data Asset
        """
        pass

    def test_delete(self) -> None:
        """Test case for delete

        Delete
        """
        pass

    def test_get_data_asset(self) -> None:
        """Test case for get_data_asset

        Get Data Asset
        """
        pass

    def test_get_data_assets(self) -> None:
        """Test case for get_data_assets

        Get Data Assets
        """
        pass

    def test_update(self) -> None:
        """Test case for update

        Update
        """
        pass


if __name__ == '__main__':
    unittest.main()
