# coding: utf-8

"""
    biodata-registry-service

     ## biodata-registry-service  Service to fetch data from Registry.  

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biodata_registry_api_client.models.data_asset_view import DataAssetView

class TestDataAssetView(unittest.TestCase):
    """DataAssetView unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataAssetView:
        """Test DataAssetView
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DataAssetView`
        """
        model = DataAssetView()
        if include_optional:
            return DataAssetView(
                data_asset_id = 56,
                acquisition_id = 56,
                subject_id = 56,
                process_id = 56,
                subject_procedure_id = 56,
                acquisition_data = { },
                processes_data = { },
                instrument_name = '',
                instrument_data = { },
                data_asset_location = '',
                data_asset_name = '',
                data_asset_data = { },
                data_asset_external_links = { },
                subject_name = '',
                subject_data = { },
                subject_procedures_data = [
                    { }
                    ],
                quality_control_data = { }
            )
        else:
            return DataAssetView(
        )
        """

    def testDataAssetView(self):
        """Test DataAssetView"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
