# coding: utf-8

"""
    biodata-registry-service

     ## biodata-registry-service  Service to fetch data from Registry.  

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biodata_registry_api_client.api.spaces_api import SpacesApi


class TestSpacesApi(unittest.TestCase):
    """SpacesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SpacesApi()

    def tearDown(self) -> None:
        pass

    def test_create_space(self) -> None:
        """Test case for create_space

        Create Space
        """
        pass

    def test_delete(self) -> None:
        """Test case for delete

        Delete
        """
        pass

    def test_get_space(self) -> None:
        """Test case for get_space

        Get Space
        """
        pass

    def test_get_spaces(self) -> None:
        """Test case for get_spaces

        Get Spaces
        """
        pass

    def test_update(self) -> None:
        """Test case for update

        Update
        """
        pass


if __name__ == '__main__':
    unittest.main()
