# coding: utf-8

"""
    biodata-registry-service

     ## biodata-registry-service  Service to fetch data from Registry.  

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biodata_registry_api_client.models.acquisitions_page import AcquisitionsPage

class TestAcquisitionsPage(unittest.TestCase):
    """AcquisitionsPage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AcquisitionsPage:
        """Test AcquisitionsPage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AcquisitionsPage`
        """
        model = AcquisitionsPage()
        if include_optional:
            return AcquisitionsPage(
                next_token = '',
                has_more = True,
                results = [
                    biodata_registry_api_client.models.acquisitions.Acquisitions(
                        id = 56, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_by = 56, 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_by = 56, 
                        data = { }, 
                        schema_id = 56, 
                        space_id = 56, 
                        data_asset_id = 56, 
                        instrument_id = 56, )
                    ]
            )
        else:
            return AcquisitionsPage(
                results = [
                    biodata_registry_api_client.models.acquisitions.Acquisitions(
                        id = 56, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_by = 56, 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_by = 56, 
                        data = { }, 
                        schema_id = 56, 
                        space_id = 56, 
                        data_asset_id = 56, 
                        instrument_id = 56, )
                    ],
        )
        """

    def testAcquisitionsPage(self):
        """Test AcquisitionsPage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
