# coding: utf-8

"""
    biodata-registry-service

     ## biodata-registry-service  Service to fetch data from Registry.  

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biodata_registry_api_client.models.subject_create import SubjectCreate

class TestSubjectCreate(unittest.TestCase):
    """SubjectCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubjectCreate:
        """Test SubjectCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubjectCreate`
        """
        model = SubjectCreate()
        if include_optional:
            return SubjectCreate(
                name = '',
                data = { },
                schema_id = 56,
                space_id = 56
            )
        else:
            return SubjectCreate(
                name = '',
        )
        """

    def testSubjectCreate(self):
        """Test SubjectCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
