# coding: utf-8

"""
    biodata-registry-service

     ## biodata-registry-service  Service to fetch data from Registry.  

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biodata_registry_api_client.api.admin_api import AdminApi


class TestAdminApi(unittest.TestCase):
    """AdminApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminApi()

    def tearDown(self) -> None:
        pass

    def test_create_collection(self) -> None:
        """Test case for create_collection

        Create Collection
        """
        pass

    def test_create_organization(self) -> None:
        """Test case for create_organization

        Create Organization
        """
        pass

    def test_create_organization_admin(self) -> None:
        """Test case for create_organization_admin

        Create Organization Admin
        """
        pass

    def test_create_space(self) -> None:
        """Test case for create_space

        Create Space
        """
        pass

    def test_create_space_admin(self) -> None:
        """Test case for create_space_admin

        Create Space Admin
        """
        pass

    def test_create_user(self) -> None:
        """Test case for create_user

        Create User
        """
        pass

    def test_delete_collection(self) -> None:
        """Test case for delete_collection

        Delete
        """
        pass

    def test_delete_organization(self) -> None:
        """Test case for delete_organization

        Delete
        """
        pass

    def test_delete_organization_admin(self) -> None:
        """Test case for delete_organization_admin

        Delete
        """
        pass

    def test_delete_space(self) -> None:
        """Test case for delete_space

        Delete
        """
        pass

    def test_delete_space_admin(self) -> None:
        """Test case for delete_space_admin

        Delete
        """
        pass

    def test_delete_user(self) -> None:
        """Test case for delete_user

        Delete
        """
        pass

    def test_get_collection(self) -> None:
        """Test case for get_collection

        Get Collection
        """
        pass

    def test_get_collection_data_assets(self) -> None:
        """Test case for get_collection_data_assets

        Get Collection Data Assets
        """
        pass

    def test_get_collections(self) -> None:
        """Test case for get_collections

        Get Collections
        """
        pass

    def test_get_organization(self) -> None:
        """Test case for get_organization

        Get Organization
        """
        pass

    def test_get_organization_admin(self) -> None:
        """Test case for get_organization_admin

        Get Organization Admin
        """
        pass

    def test_get_organization_admins(self) -> None:
        """Test case for get_organization_admins

        Get Organization Admins
        """
        pass

    def test_get_organizations(self) -> None:
        """Test case for get_organizations

        Get Organizations
        """
        pass

    def test_get_space(self) -> None:
        """Test case for get_space

        Get Space
        """
        pass

    def test_get_space_admin(self) -> None:
        """Test case for get_space_admin

        Get Space Admin
        """
        pass

    def test_get_space_admins(self) -> None:
        """Test case for get_space_admins

        Get Space Admins
        """
        pass

    def test_get_spaces(self) -> None:
        """Test case for get_spaces

        Get Spaces
        """
        pass

    def test_get_user(self) -> None:
        """Test case for get_user

        Get User
        """
        pass

    def test_get_users(self) -> None:
        """Test case for get_users

        Get Users
        """
        pass

    def test_put_collection_data_asset(self) -> None:
        """Test case for put_collection_data_asset

        Add Collection Data Asset
        """
        pass

    def test_remove_collection_data_asset(self) -> None:
        """Test case for remove_collection_data_asset

        Remove Collection Data Asset
        """
        pass

    def test_update_collection(self) -> None:
        """Test case for update_collection

        Update
        """
        pass

    def test_update_organization(self) -> None:
        """Test case for update_organization

        Update
        """
        pass

    def test_update_organization_admin(self) -> None:
        """Test case for update_organization_admin

        Update
        """
        pass

    def test_update_space(self) -> None:
        """Test case for update_space

        Update
        """
        pass

    def test_update_space_admin(self) -> None:
        """Test case for update_space_admin

        Update
        """
        pass

    def test_update_user(self) -> None:
        """Test case for update_user

        Update
        """
        pass


if __name__ == '__main__':
    unittest.main()
