# coding: utf-8

"""
    biodata-registry-service

     ## biodata-registry-service  Service to fetch data from Registry.  

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biodata_registry_api_client.models.space_create import SpaceCreate

class TestSpaceCreate(unittest.TestCase):
    """SpaceCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SpaceCreate:
        """Test SpaceCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SpaceCreate`
        """
        model = SpaceCreate()
        if include_optional:
            return SpaceCreate(
                name = '',
                organization_id = 56
            )
        else:
            return SpaceCreate(
                name = '',
        )
        """

    def testSpaceCreate(self):
        """Test SpaceCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
