# coding: utf-8

"""
    biodata-registry-service

     ## biodata-registry-service  Service to fetch data from Registry.  

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biodata_registry_api_client.api.views_api import ViewsApi


class TestViewsApi(unittest.TestCase):
    """ViewsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ViewsApi()

    def tearDown(self) -> None:
        pass

    def test_get_data_asset_view(self) -> None:
        """Test case for get_data_asset_view

        Get Data Asset View
        """
        pass


if __name__ == '__main__':
    unittest.main()
