# coding: utf-8

"""
    biodata-registry-service

     ## biodata-registry-service  Service to fetch data from Registry.  

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biodata_registry_api_client.api.schema_entities_api import SchemaEntitiesApi


class TestSchemaEntitiesApi(unittest.TestCase):
    """SchemaEntitiesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SchemaEntitiesApi()

    def tearDown(self) -> None:
        pass

    def test_create_schema_entity(self) -> None:
        """Test case for create_schema_entity

        Create Schema Entity
        """
        pass

    def test_delete(self) -> None:
        """Test case for delete

        Delete
        """
        pass

    def test_get_schema_entities(self) -> None:
        """Test case for get_schema_entities

        Get Schema Entities
        """
        pass

    def test_get_schema_entity(self) -> None:
        """Test case for get_schema_entity

        Get Schema Entity
        """
        pass

    def test_update(self) -> None:
        """Test case for update

        Update
        """
        pass


if __name__ == '__main__':
    unittest.main()
