# coding: utf-8

"""
    biodata-registry-service

     ## biodata-registry-service  Service to fetch data from Registry.  

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biodata_registry_api_client.models.data_asset_views_page import DataAssetViewsPage

class TestDataAssetViewsPage(unittest.TestCase):
    """DataAssetViewsPage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataAssetViewsPage:
        """Test DataAssetViewsPage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DataAssetViewsPage`
        """
        model = DataAssetViewsPage()
        if include_optional:
            return DataAssetViewsPage(
                next_token = '',
                has_more = True,
                results = [
                    biodata_registry_api_client.models.data_asset_view.DataAssetView(
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_by = 56, 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_by = 56, 
                        data_asset_id = 56, 
                        acquisition_id = 56, 
                        process_id = 56, 
                        instrument_id = 56, 
                        acquisition_data = { }, 
                        processes_data = { }, 
                        instrument_name = '', 
                        instrument_data = { }, 
                        data_asset_location = '', 
                        data_asset_name = '', 
                        data_asset_data = { }, 
                        data_asset_external_links = { }, 
                        subjects = [
                            { }
                            ], 
                        subject_procedures = [
                            { }
                            ], 
                        quality_control_metrics = [
                            { }
                            ], )
                    ]
            )
        else:
            return DataAssetViewsPage(
                results = [
                    biodata_registry_api_client.models.data_asset_view.DataAssetView(
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_by = 56, 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_by = 56, 
                        data_asset_id = 56, 
                        acquisition_id = 56, 
                        process_id = 56, 
                        instrument_id = 56, 
                        acquisition_data = { }, 
                        processes_data = { }, 
                        instrument_name = '', 
                        instrument_data = { }, 
                        data_asset_location = '', 
                        data_asset_name = '', 
                        data_asset_data = { }, 
                        data_asset_external_links = { }, 
                        subjects = [
                            { }
                            ], 
                        subject_procedures = [
                            { }
                            ], 
                        quality_control_metrics = [
                            { }
                            ], )
                    ],
        )
        """

    def testDataAssetViewsPage(self):
        """Test DataAssetViewsPage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
