# coding: utf-8

"""
    biodata-registry-service

     ## biodata-registry-service  Service to fetch data from Registry.  

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biodata_registry_api_client.models.collections import Collections

class TestCollections(unittest.TestCase):
    """Collections unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Collections:
        """Test Collections
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Collections`
        """
        model = Collections()
        if include_optional:
            return Collections(
                id = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_by = 56,
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_by = 56,
                name = '',
                description = '',
                owner_id = 56
            )
        else:
            return Collections(
                name = '',
                description = '',
        )
        """

    def testCollections(self):
        """Test Collections"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
