# coding: utf-8

"""
    biodata-registry-service

     ## biodata-registry-service  Service to fetch data from Registry.  

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biodata_registry_api_client.models.acquisitions import Acquisitions

class TestAcquisitions(unittest.TestCase):
    """Acquisitions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Acquisitions:
        """Test Acquisitions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Acquisitions`
        """
        model = Acquisitions()
        if include_optional:
            return Acquisitions(
                id = 56,
                data = { },
                schema_id = 56,
                space_id = 56,
                data_asset_id = 56,
                instrument_id = 56
            )
        else:
            return Acquisitions(
        )
        """

    def testAcquisitions(self):
        """Test Acquisitions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
