# coding: utf-8

"""
    biodata-registry-service

     ## biodata-registry-service  Service to fetch data from Registry.  

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biodata_registry_api_client.api.core_api import CoreApi


class TestCoreApi(unittest.TestCase):
    """CoreApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CoreApi()

    def tearDown(self) -> None:
        pass

    def test_create_acquisition(self) -> None:
        """Test case for create_acquisition

        Create Acquisition
        """
        pass

    def test_create_data_asset(self) -> None:
        """Test case for create_data_asset

        Create Data Asset
        """
        pass

    def test_create_instrument(self) -> None:
        """Test case for create_instrument

        Create Instrument
        """
        pass

    def test_create_process(self) -> None:
        """Test case for create_process

        Create Process
        """
        pass

    def test_create_quality_control(self) -> None:
        """Test case for create_quality_control

        Create Quality Control
        """
        pass

    def test_create_schema(self) -> None:
        """Test case for create_schema

        Create Schema
        """
        pass

    def test_create_schema_entity(self) -> None:
        """Test case for create_schema_entity

        Create Schema Entity
        """
        pass

    def test_create_specimen(self) -> None:
        """Test case for create_specimen

        Create Specimen
        """
        pass

    def test_create_specimen_procedure(self) -> None:
        """Test case for create_specimen_procedure

        Create Specimen Procedure
        """
        pass

    def test_create_subject(self) -> None:
        """Test case for create_subject

        Create Subject
        """
        pass

    def test_create_subject_procedure(self) -> None:
        """Test case for create_subject_procedure

        Create Subject Procedure
        """
        pass

    def test_delete_acquisition(self) -> None:
        """Test case for delete_acquisition

        Delete
        """
        pass

    def test_delete_data_asset(self) -> None:
        """Test case for delete_data_asset

        Delete
        """
        pass

    def test_delete_instrument(self) -> None:
        """Test case for delete_instrument

        Delete
        """
        pass

    def test_delete_process(self) -> None:
        """Test case for delete_process

        Delete
        """
        pass

    def test_delete_quality_control(self) -> None:
        """Test case for delete_quality_control

        Delete
        """
        pass

    def test_delete_schema(self) -> None:
        """Test case for delete_schema

        Delete
        """
        pass

    def test_delete_schema_entity(self) -> None:
        """Test case for delete_schema_entity

        Delete
        """
        pass

    def test_delete_specimen(self) -> None:
        """Test case for delete_specimen

        Delete
        """
        pass

    def test_delete_specimen_procedure(self) -> None:
        """Test case for delete_specimen_procedure

        Delete
        """
        pass

    def test_delete_subject(self) -> None:
        """Test case for delete_subject

        Delete
        """
        pass

    def test_delete_subject_procedure(self) -> None:
        """Test case for delete_subject_procedure

        Delete
        """
        pass

    def test_get_acquisition(self) -> None:
        """Test case for get_acquisition

        Get Acquisition
        """
        pass

    def test_get_acquisition_specimens(self) -> None:
        """Test case for get_acquisition_specimens

        Get Acquisition Subjects
        """
        pass

    def test_get_acquisition_subjects(self) -> None:
        """Test case for get_acquisition_subjects

        Get Acquisition Subjects
        """
        pass

    def test_get_acquisitions(self) -> None:
        """Test case for get_acquisitions

        Get Acquisitions
        """
        pass

    def test_get_data_asset(self) -> None:
        """Test case for get_data_asset

        Get Data Asset
        """
        pass

    def test_get_data_asset_collections(self) -> None:
        """Test case for get_data_asset_collections

        Get Data Asset Collections
        """
        pass

    def test_get_data_asset_process_inputs(self) -> None:
        """Test case for get_data_asset_process_inputs

        Get Data Asset Process Inputs
        """
        pass

    def test_get_data_assets(self) -> None:
        """Test case for get_data_assets

        Get Data Assets
        """
        pass

    def test_get_instrument(self) -> None:
        """Test case for get_instrument

        Get Instrument
        """
        pass

    def test_get_instruments(self) -> None:
        """Test case for get_instruments

        Get Instruments
        """
        pass

    def test_get_process(self) -> None:
        """Test case for get_process

        Get Process
        """
        pass

    def test_get_process_data_asset_inputs(self) -> None:
        """Test case for get_process_data_asset_inputs

        Get Process Data Asset Inputs
        """
        pass

    def test_get_processes(self) -> None:
        """Test case for get_processes

        Get Processes
        """
        pass

    def test_get_quality_control(self) -> None:
        """Test case for get_quality_control

        Get Quality Control
        """
        pass

    def test_get_quality_controls(self) -> None:
        """Test case for get_quality_controls

        Get Quality Controls
        """
        pass

    def test_get_schema(self) -> None:
        """Test case for get_schema

        Get Schema
        """
        pass

    def test_get_schema_entities(self) -> None:
        """Test case for get_schema_entities

        Get Schema Entities
        """
        pass

    def test_get_schema_entity(self) -> None:
        """Test case for get_schema_entity

        Get Schema Entity
        """
        pass

    def test_get_schemas(self) -> None:
        """Test case for get_schemas

        Get Schemas
        """
        pass

    def test_get_specimen(self) -> None:
        """Test case for get_specimen

        Get Specimen
        """
        pass

    def test_get_specimen_acquisitions(self) -> None:
        """Test case for get_specimen_acquisitions

        Get Specimen Acquisitions
        """
        pass

    def test_get_specimen_procedure(self) -> None:
        """Test case for get_specimen_procedure

        Get Specimen Procedure
        """
        pass

    def test_get_specimen_procedure_specimen_inputs(self) -> None:
        """Test case for get_specimen_procedure_specimen_inputs

        Get Specimen Procedure Specimen Inputs
        """
        pass

    def test_get_specimen_procedure_specimen_outputs(self) -> None:
        """Test case for get_specimen_procedure_specimen_outputs

        Get Specimen Procedure Specimen Outputs
        """
        pass

    def test_get_specimen_procedures(self) -> None:
        """Test case for get_specimen_procedures

        Get Specimen Procedures
        """
        pass

    def test_get_specimen_specimen_procedure_inputs(self) -> None:
        """Test case for get_specimen_specimen_procedure_inputs

        Get Specimen Specimen Procedure Inputs
        """
        pass

    def test_get_specimen_specimen_procedure_outputs(self) -> None:
        """Test case for get_specimen_specimen_procedure_outputs

        Get Specimen Specimen Procedure Outputs
        """
        pass

    def test_get_specimen_subject_procedures(self) -> None:
        """Test case for get_specimen_subject_procedures

        Get Specimen Subject Procedures
        """
        pass

    def test_get_specimens(self) -> None:
        """Test case for get_specimens

        Get Specimens
        """
        pass

    def test_get_subject(self) -> None:
        """Test case for get_subject

        Get Subject
        """
        pass

    def test_get_subject_acquisitions(self) -> None:
        """Test case for get_subject_acquisitions

        Get Subject Acquisitions
        """
        pass

    def test_get_subject_procedure(self) -> None:
        """Test case for get_subject_procedure

        Get Subject Procedure
        """
        pass

    def test_get_subject_procedure_specimens(self) -> None:
        """Test case for get_subject_procedure_specimens

        Get Subject Procedure Specimens
        """
        pass

    def test_get_subject_procedures(self) -> None:
        """Test case for get_subject_procedures

        Get Subject Procedures
        """
        pass

    def test_get_subjects(self) -> None:
        """Test case for get_subjects

        Get Subjects
        """
        pass

    def test_put_acquisition_specimen(self) -> None:
        """Test case for put_acquisition_specimen

        Add Acquisition Specimen
        """
        pass

    def test_put_acquisition_subject(self) -> None:
        """Test case for put_acquisition_subject

        Add Acquisition Subject
        """
        pass

    def test_put_data_asset_collection(self) -> None:
        """Test case for put_data_asset_collection

        Add Data Asset Collection
        """
        pass

    def test_put_data_asset_process_input(self) -> None:
        """Test case for put_data_asset_process_input

        Add Data Asset Process Input
        """
        pass

    def test_put_process_data_asset_input(self) -> None:
        """Test case for put_process_data_asset_input

        Add Process Data Asset Input
        """
        pass

    def test_put_specimen_acquisition(self) -> None:
        """Test case for put_specimen_acquisition

        Add Specimen Acquisition
        """
        pass

    def test_put_specimen_procedure_specimen_input(self) -> None:
        """Test case for put_specimen_procedure_specimen_input

        Add Specimen Procedure Specimen Input
        """
        pass

    def test_put_specimen_procedure_specimen_output(self) -> None:
        """Test case for put_specimen_procedure_specimen_output

        Add Specimen Procedure Specimen Output
        """
        pass

    def test_put_specimen_specimen_procedure_input(self) -> None:
        """Test case for put_specimen_specimen_procedure_input

        Add Specimen Specimen Procedure Input
        """
        pass

    def test_put_specimen_specimen_procedure_output(self) -> None:
        """Test case for put_specimen_specimen_procedure_output

        Add Specimen Specimen Procedure Output
        """
        pass

    def test_put_specimen_subject_procedure(self) -> None:
        """Test case for put_specimen_subject_procedure

        Add Specimen Subject Procedure
        """
        pass

    def test_put_subject_acquisition(self) -> None:
        """Test case for put_subject_acquisition

        Add Subject Acquisition
        """
        pass

    def test_put_subject_procedure_specimen(self) -> None:
        """Test case for put_subject_procedure_specimen

        Add Subject Procedure Specimen
        """
        pass

    def test_remove_acquisition_specimen(self) -> None:
        """Test case for remove_acquisition_specimen

        Remove Acquisition Specimen
        """
        pass

    def test_remove_acquisition_subject(self) -> None:
        """Test case for remove_acquisition_subject

        Remove Acquisition Subject
        """
        pass

    def test_remove_data_asset_collection(self) -> None:
        """Test case for remove_data_asset_collection

        Remove Collection Data Asset
        """
        pass

    def test_remove_data_asset_process_input(self) -> None:
        """Test case for remove_data_asset_process_input

        Remove Data Asset Process Input
        """
        pass

    def test_remove_process_data_asset_input(self) -> None:
        """Test case for remove_process_data_asset_input

        Remove Process Data Asset Input
        """
        pass

    def test_remove_specimen_acquisition(self) -> None:
        """Test case for remove_specimen_acquisition

        Remove Specimen Acquisition
        """
        pass

    def test_remove_specimen_procedure_specimen_input(self) -> None:
        """Test case for remove_specimen_procedure_specimen_input

        Remove Specimen Procedure Specimen Input
        """
        pass

    def test_remove_specimen_procedure_specimen_output(self) -> None:
        """Test case for remove_specimen_procedure_specimen_output

        Remove Specimen Procedure Specimen Output
        """
        pass

    def test_remove_specimen_specimen_procedure_input(self) -> None:
        """Test case for remove_specimen_specimen_procedure_input

        Remove Specimen Specimen Procedure Input
        """
        pass

    def test_remove_specimen_specimen_procedure_output(self) -> None:
        """Test case for remove_specimen_specimen_procedure_output

        Remove Specimen Specimen Procedure Output
        """
        pass

    def test_remove_specimen_subject_procedure(self) -> None:
        """Test case for remove_specimen_subject_procedure

        Remove Specimen Subject Procedure
        """
        pass

    def test_remove_subject_acquisition(self) -> None:
        """Test case for remove_subject_acquisition

        Remove Subject Acquisition
        """
        pass

    def test_remove_subject_procedure_specimen(self) -> None:
        """Test case for remove_subject_procedure_specimen

        Remove Subject Procedure Specimen
        """
        pass

    def test_update_acquisition(self) -> None:
        """Test case for update_acquisition

        Update
        """
        pass

    def test_update_data_asset(self) -> None:
        """Test case for update_data_asset

        Update
        """
        pass

    def test_update_instrument(self) -> None:
        """Test case for update_instrument

        Update
        """
        pass

    def test_update_process(self) -> None:
        """Test case for update_process

        Update
        """
        pass

    def test_update_quality_control(self) -> None:
        """Test case for update_quality_control

        Update
        """
        pass

    def test_update_schema(self) -> None:
        """Test case for update_schema

        Update
        """
        pass

    def test_update_schema_entity(self) -> None:
        """Test case for update_schema_entity

        Update
        """
        pass

    def test_update_specimen(self) -> None:
        """Test case for update_specimen

        Update
        """
        pass

    def test_update_specimen_procedure(self) -> None:
        """Test case for update_specimen_procedure

        Update
        """
        pass

    def test_update_subject(self) -> None:
        """Test case for update_subject

        Update
        """
        pass

    def test_update_subject_procedure(self) -> None:
        """Test case for update_subject_procedure

        Update
        """
        pass


if __name__ == '__main__':
    unittest.main()
