# coding: utf-8

"""
    biodata-registry-service

     ## biodata-registry-service  Service to fetch data from Registry.  

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biodata_registry_api_client.models.data_assets_page import DataAssetsPage

class TestDataAssetsPage(unittest.TestCase):
    """DataAssetsPage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataAssetsPage:
        """Test DataAssetsPage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DataAssetsPage`
        """
        model = DataAssetsPage()
        if include_optional:
            return DataAssetsPage(
                next_token = '',
                has_more = True,
                results = [
                    biodata_registry_api_client.models.data_assets.DataAssets(
                        id = 56, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_by = 56, 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_by = 56, 
                        name = '', 
                        location = '', 
                        external_links = { }, 
                        data = { }, 
                        schema_id = 56, 
                        space_id = 56, )
                    ]
            )
        else:
            return DataAssetsPage(
                results = [
                    biodata_registry_api_client.models.data_assets.DataAssets(
                        id = 56, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_by = 56, 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_by = 56, 
                        name = '', 
                        location = '', 
                        external_links = { }, 
                        data = { }, 
                        schema_id = 56, 
                        space_id = 56, )
                    ],
        )
        """

    def testDataAssetsPage(self):
        """Test DataAssetsPage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
