# coding: utf-8

"""
    biodata-registry-service

     ## biodata-registry-service  Service to fetch data from Registry.  

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biodata_registry_api_client.api.organization_admins_api import OrganizationAdminsApi


class TestOrganizationAdminsApi(unittest.TestCase):
    """OrganizationAdminsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrganizationAdminsApi()

    def tearDown(self) -> None:
        pass

    def test_create_organization_admin(self) -> None:
        """Test case for create_organization_admin

        Create Organization Admin
        """
        pass

    def test_delete(self) -> None:
        """Test case for delete

        Delete
        """
        pass

    def test_get_organization_admin(self) -> None:
        """Test case for get_organization_admin

        Get Organization Admin
        """
        pass

    def test_get_organization_admins(self) -> None:
        """Test case for get_organization_admins

        Get Organization Admins
        """
        pass

    def test_update(self) -> None:
        """Test case for update

        Update
        """
        pass


if __name__ == '__main__':
    unittest.main()
