# coding: utf-8

"""
    biodata-registry-service

     ## biodata-registry-service  Service to fetch data from Registry.  

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biodata_registry_api_client.api.collections_api import CollectionsApi


class TestCollectionsApi(unittest.TestCase):
    """CollectionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CollectionsApi()

    def tearDown(self) -> None:
        pass

    def test_create_collection(self) -> None:
        """Test case for create_collection

        Create Collection
        """
        pass

    def test_delete(self) -> None:
        """Test case for delete

        Delete
        """
        pass

    def test_get_collection(self) -> None:
        """Test case for get_collection

        Get Collection
        """
        pass

    def test_get_collections(self) -> None:
        """Test case for get_collections

        Get Collections
        """
        pass

    def test_update(self) -> None:
        """Test case for update

        Update
        """
        pass


if __name__ == '__main__':
    unittest.main()
