# coding: utf-8

"""
    biodata-registry-service

     ## biodata-registry-service  Service to fetch data from Registry.  

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biodata_registry_api_client.models.data_assets import DataAssets

class TestDataAssets(unittest.TestCase):
    """DataAssets unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataAssets:
        """Test DataAssets
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DataAssets`
        """
        model = DataAssets()
        if include_optional:
            return DataAssets(
                name = '',
                location = '',
                external_links = { },
                data = { },
                schema_id = 56,
                space_id = 56,
                id = 56
            )
        else:
            return DataAssets(
                name = '',
                location = '',
        )
        """

    def testDataAssets(self):
        """Test DataAssets"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
