# coding: utf-8

"""
    biodata-registry-service

     ## biodata-registry-service  Service to fetch data from Registry.  

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biodata_registry_api_client.api.healthcheck_api import HealthcheckApi


class TestHealthcheckApi(unittest.TestCase):
    """HealthcheckApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HealthcheckApi()

    def tearDown(self) -> None:
        pass

    def test_get_health(self) -> None:
        """Test case for get_health

        Perform a Health Check
        """
        pass


if __name__ == '__main__':
    unittest.main()
