# coding: utf-8

"""
    biodata-registry-service

     ## biodata-registry-service  Service to fetch data from Registry.  

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from biodata_registry_api_client.api.schemas_api import SchemasApi


class TestSchemasApi(unittest.TestCase):
    """SchemasApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SchemasApi()

    def tearDown(self) -> None:
        pass

    def test_create_schema(self) -> None:
        """Test case for create_schema

        Create Schema
        """
        pass

    def test_delete(self) -> None:
        """Test case for delete

        Delete
        """
        pass

    def test_get_schema(self) -> None:
        """Test case for get_schema

        Get Schema
        """
        pass

    def test_get_schemas(self) -> None:
        """Test case for get_schemas

        Get Schemas
        """
        pass

    def test_update(self) -> None:
        """Test case for update

        Update
        """
        pass


if __name__ == '__main__':
    unittest.main()
