services:
  zookeeper:
    image: quay.io/debezium/zookeeper:3.1
    ports: ["2181:2181"]

  kafka:
    image: quay.io/debezium/kafka:3.1
    depends_on: [zookeeper]
    ports: ["29092:29092"]
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  connect:
    image: quay.io/debezium/connect:3.1
    depends_on: [kafka]
    ports: ["8083:8083"]
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"

  postgres:
    image: debezium/postgres:15
    command: postgres -c wal_level=logical -c max_wal_senders=10 -c max_replication_slots=10
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: registry
    ports: ["5432:5432"]
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql

  api:
    build: ./api
    container_name: registry_api
    depends_on: [postgres]
    ports: ["5000:80"]
    environment:
      REGISTRY_HOST: postgres
      REGISTRY_USER: user
      REGISTRY_PORT: 5432
      REGISTRY_PASSWORD: password
      REGISTRY_DATABASE: registry

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports: ["27017:27017"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_password
    volumes:
      - mongo_data:/data/db

  register_connector_sidecar:
    build: ./register_connector_sidecar
    container_name: register_connector_sidecar
    depends_on: [connect]
    environment:
      CONNECT_URL: "http://connect:8083/connectors"
      PG_USER: user
      PG_PASSWORD: password
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DBNAME: registry
    entrypoint: ["python", "-u", "register_connector.py"]

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:9.3.3
#    container_name: elasticsearch
#    environment:
#      - discovery.type=single-node
#      - xpack.security.enabled=false
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ports: [ "9200:9200" ]
#    volumes:
#      - es_data:/usr/share/elasticsearch/data
#    healthcheck:
#      test: [ "CMD-SHELL", "curl -s http://localhost:9200 >/dev/null || exit 1" ]
#      interval: 10s
#      timeout: 10s
#      retries: 5

#  register_es_index_sidecar:
#    build: ./register_es_index_sidecar
#    container_name: register_es_index_sidecar
#    depends_on:
#      elasticsearch:
#        condition: service_healthy
#    environment:
#      ES_INDEX_URL: "http://elasticsearch:9200/data_assets"
#    entrypoint: [ "python", "-u", "register_es_index.py" ]

  lambda:
    build: ./lambda
    container_name: lambda
    depends_on:
      register_connector_sidecar:
        condition: service_completed_successfully
      mongodb:
        condition: service_started
#      register_es_index_sidecar:
#        condition: service_completed_successfully
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USERNAME: admin
      MONGO_PASSWORD: admin_password
      MONGO_DBNAME: metadata
      MONGO_DB_COLLECTION: data_assets
      PG_USER: user
      PG_PASSWORD: password
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DBNAME: registry
      KAFKA_SERVER: "kafka:9092"
      ES_URL: "http://elasticsearch:9200"
      ES_INDEX: data_assets
    entrypoint: ["python", "-u", "sync_registry_docdb.py"]

volumes:
  postgres_data:
  mongo_data:
#  es_data:
