-- Connect to database
\c mydatabase;

-- Create admin tables
CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(254) NOT NULL,
    contact VARCHAR(254) NOT NULL
);

CREATE TABLE IF NOT EXISTS organizations (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(254) NOT NULL
);

CREATE TABLE IF NOT EXISTS spaces (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(254) NOT NULL,
    organization_id INT NOT NULL,
    CONSTRAINT fk_organization_id
        FOREIGN KEY (organization_id)
        REFERENCES organizations(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS space_admins (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    space_id INT NOT NULL,
    CONSTRAINT fk_space_id
        FOREIGN KEY (space_id)
        REFERENCES spaces(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT fk_user_id
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS organization_admins (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    organization_id INT NOT NULL,
    CONSTRAINT fk_organization_id
        FOREIGN KEY (organization_id)
        REFERENCES organizations(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT fk_user_id
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS collections (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(254) NOT NULL,
    description VARCHAR(254),
    owner_id INT NOT NULL,
    CONSTRAINT fk_owner_id
        FOREIGN KEY (owner_id)
        REFERENCES users(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
);

-- Create core tables
CREATE TABLE IF NOT EXISTS schema_entities (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS schemas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    version VARCHAR(50) NOT NULL,
    data JSONB NOT NULL,
    schema_entity_id INT NOT NULL,
    CONSTRAINT fk_schema_entity_id
        FOREIGN KEY (schema_entity_id)
        REFERENCES schema_entities(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS processes (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data JSONB NOT NULL,
    schema_id INT NOT NULL,
    space_id INT NOT NULL,
    CONSTRAINT fk_schema_id
        FOREIGN KEY (schema_id)
        REFERENCES schemas(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT fk_space_id
        FOREIGN KEY (space_id)
        REFERENCES spaces(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS subjects (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data JSONB NOT NULL,
    name VARCHAR(50) NOT NULL,
    schema_id INT NOT NULL,
    space_id INT NOT NULL,
    CONSTRAINT fk_schema_id
        FOREIGN KEY (schema_id)
        REFERENCES schemas(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT fk_space_id
        FOREIGN KEY (space_id)
        REFERENCES spaces(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS specimens (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data JSONB NOT NULL,
    name VARCHAR(50) NOT NULL,
    schema_id INT NOT NULL,
    space_id INT NOT NULL,
    subject_id INT NOT NULL,
    CONSTRAINT fk_schema_id
        FOREIGN KEY (schema_id)
        REFERENCES schemas(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT fk_space_id
        FOREIGN KEY (space_id)
        REFERENCES spaces(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT fk_subject_id
        FOREIGN KEY (subject_id)
        REFERENCES subjects(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS subject_procedures (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data JSONB NOT NULL,
    schema_id INT NOT NULL,
    space_id INT NOT NULL,
    subject_id INT NOT NULL,
    CONSTRAINT fk_schema_id
        FOREIGN KEY (schema_id)
        REFERENCES schemas(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT fk_space_id
        FOREIGN KEY (space_id)
        REFERENCES spaces(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT fk_subject_id
        FOREIGN KEY (subject_id)
        REFERENCES subjects(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS specimen_procedures (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data JSONB NOT NULL,
    schema_id INT NOT NULL,
    space_id INT NOT NULL,
    CONSTRAINT fk_schema_id
        FOREIGN KEY (schema_id)
        REFERENCES schemas(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT fk_space_id
        FOREIGN KEY (space_id)
        REFERENCES spaces(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS data_assets (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(254) NOT NULL,
    location VARCHAR(254) NOT NULL,
    -- external_links JSONB,
    data JSONB NOT NULL,
    schema_id INT NOT NULL,
    space_id INT NOT NULL,
    CONSTRAINT fk_schema_id
        FOREIGN KEY (schema_id)
        REFERENCES schemas(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT fk_space_id
        FOREIGN KEY (space_id)
        REFERENCES spaces(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS quality_control (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data JSONB NOT NULL,
    schema_id INT NOT NULL,
    space_id INT NOT NULL,
    data_asset_id INT NOT NULL,
    CONSTRAINT fk_schema_id
        FOREIGN KEY (schema_id)
        REFERENCES schemas(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT fk_space_id
        FOREIGN KEY (space_id)
        REFERENCES spaces(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT fk_data_asset_id
        FOREIGN KEY (data_asset_id)
        REFERENCES data_assets(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS instruments (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    data JSONB NOT NULL,
    schema_id INT NOT NULL,
    space_id INT NOT NULL,
    CONSTRAINT fk_schema_id
        FOREIGN KEY (schema_id)
        REFERENCES schemas(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT fk_space_id
        FOREIGN KEY (space_id)
        REFERENCES spaces(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS acquisitions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data JSONB NOT NULL,
    schema_id INT NOT NULL,
    space_id INT NOT NULL,
    data_asset_id INT NOT NULL,
    instrument_id INT NOT NULL,
    CONSTRAINT fk_schema_id
        FOREIGN KEY (schema_id)
        REFERENCES schemas(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT fk_space_id
        FOREIGN KEY (space_id)
        REFERENCES spaces(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT fk_data_asset_id
        FOREIGN KEY (data_asset_id)
        REFERENCES data_assets(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION,
    CONSTRAINT fk_instrument_id
        FOREIGN KEY (instrument_id)
        REFERENCES instruments(id)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
);

-- Create join tables
CREATE TABLE process_inputs (
    data_asset_id INT REFERENCES data_assets(id) ON DELETE CASCADE,
    process_id INT REFERENCES processes(id) ON DELETE CASCADE,
    PRIMARY KEY (data_asset_id, process_id)
);

CREATE TABLE process_outputs (
    data_asset_id INT REFERENCES data_assets(id) ON DELETE CASCADE,
    process_id INT REFERENCES processes(id) ON DELETE CASCADE,
    PRIMARY KEY (data_asset_id, process_id)
);

CREATE TABLE subject_procedure_outputs (
    specimen_id INT REFERENCES specimens(id) ON DELETE CASCADE,
    subject_procedure_id INT REFERENCES subject_procedures(id) ON DELETE CASCADE,
    PRIMARY KEY (specimen_id, subject_procedure_id)
);

CREATE TABLE specimen_procedure_inputs (
    specimen_id INT REFERENCES specimens(id) ON DELETE CASCADE,
    specimen_procedure_id INT REFERENCES specimen_procedures(id) ON DELETE CASCADE,
    PRIMARY KEY (specimen_id, specimen_procedure_id)
);

CREATE TABLE specimen_procedure_outputs (
    specimen_id INT REFERENCES specimens(id) ON DELETE CASCADE,
    specimen_procedure_id INT REFERENCES specimen_procedures(id) ON DELETE CASCADE,
    PRIMARY KEY (specimen_id, specimen_procedure_id)
);

CREATE TABLE acquisition_subjects (
    acquisition_id INT REFERENCES acquisitions(id) ON DELETE CASCADE,
    subject_id INT REFERENCES subjects(id) ON DELETE CASCADE,
    PRIMARY KEY (acquisition_id, subject_id)
);

CREATE TABLE acquisition_specimens (
    acquisition_id INT REFERENCES acquisitions(id) ON DELETE CASCADE,
    specimen_id INT REFERENCES specimens(id) ON DELETE CASCADE,
    PRIMARY KEY (acquisition_id, specimen_id)
);

CREATE TABLE collection_data_assets (
    collection_id INT REFERENCES collections(id) ON DELETE CASCADE,
    data_asset_id INT REFERENCES data_assets(id) ON DELETE CASCADE,
    PRIMARY KEY (collection_id, data_asset_id)
);
