"""
    biodata-registry-service

     ## biodata-registry-service  Service to fetch data from Registry.  

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictInt, StrictStr
from typing import List, Optional
from typing_extensions import Annotated
from biodata_registry_api_client.models.data_asset_view import DataAssetView

from biodata_registry_api_client.api_client import ApiClient, RequestSerialized
from biodata_registry_api_client.api_response import ApiResponse
from biodata_registry_api_client.rest import RESTResponseType


class ViewsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_data_asset_view(
        self,
        data_asset_id: Optional[StrictInt] = None,
        acquisition_id: Optional[StrictInt] = None,
        subject_id: Optional[StrictInt] = None,
        subject_procedure_id: Optional[StrictInt] = None,
        instrument_id: Optional[StrictInt] = None,
        data_asset_name: Optional[StrictStr] = None,
        subject_name: Optional[StrictStr] = None,
        instrument_name: Optional[StrictStr] = None,
        data_asset_location: Optional[StrictStr] = None,
        offset: Optional[StrictInt] = None,
        limit: Optional[Annotated[int, Field(le=1000, strict=True)]] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[DataAssetView]:
        """Get Data Asset View


        :param data_asset_id:
        :type data_asset_id: int
        :param acquisition_id:
        :type acquisition_id: int
        :param subject_id:
        :type subject_id: int
        :param subject_procedure_id:
        :type subject_procedure_id: int
        :param instrument_id:
        :type instrument_id: int
        :param data_asset_name:
        :type data_asset_name: str
        :param subject_name:
        :type subject_name: str
        :param instrument_name:
        :type instrument_name: str
        :param data_asset_location:
        :type data_asset_location: str
        :param offset:
        :type offset: int
        :param limit:
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_data_asset_view_serialize(
            data_asset_id=data_asset_id,
            acquisition_id=acquisition_id,
            subject_id=subject_id,
            subject_procedure_id=subject_procedure_id,
            instrument_id=instrument_id,
            data_asset_name=data_asset_name,
            subject_name=subject_name,
            instrument_name=instrument_name,
            data_asset_location=data_asset_location,
            offset=offset,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[DataAssetView]",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_data_asset_view_with_http_info(
        self,
        data_asset_id: Optional[StrictInt] = None,
        acquisition_id: Optional[StrictInt] = None,
        subject_id: Optional[StrictInt] = None,
        subject_procedure_id: Optional[StrictInt] = None,
        instrument_id: Optional[StrictInt] = None,
        data_asset_name: Optional[StrictStr] = None,
        subject_name: Optional[StrictStr] = None,
        instrument_name: Optional[StrictStr] = None,
        data_asset_location: Optional[StrictStr] = None,
        offset: Optional[StrictInt] = None,
        limit: Optional[Annotated[int, Field(le=1000, strict=True)]] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[DataAssetView]]:
        """Get Data Asset View


        :param data_asset_id:
        :type data_asset_id: int
        :param acquisition_id:
        :type acquisition_id: int
        :param subject_id:
        :type subject_id: int
        :param subject_procedure_id:
        :type subject_procedure_id: int
        :param instrument_id:
        :type instrument_id: int
        :param data_asset_name:
        :type data_asset_name: str
        :param subject_name:
        :type subject_name: str
        :param instrument_name:
        :type instrument_name: str
        :param data_asset_location:
        :type data_asset_location: str
        :param offset:
        :type offset: int
        :param limit:
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_data_asset_view_serialize(
            data_asset_id=data_asset_id,
            acquisition_id=acquisition_id,
            subject_id=subject_id,
            subject_procedure_id=subject_procedure_id,
            instrument_id=instrument_id,
            data_asset_name=data_asset_name,
            subject_name=subject_name,
            instrument_name=instrument_name,
            data_asset_location=data_asset_location,
            offset=offset,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[DataAssetView]",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_data_asset_view_without_preload_content(
        self,
        data_asset_id: Optional[StrictInt] = None,
        acquisition_id: Optional[StrictInt] = None,
        subject_id: Optional[StrictInt] = None,
        subject_procedure_id: Optional[StrictInt] = None,
        instrument_id: Optional[StrictInt] = None,
        data_asset_name: Optional[StrictStr] = None,
        subject_name: Optional[StrictStr] = None,
        instrument_name: Optional[StrictStr] = None,
        data_asset_location: Optional[StrictStr] = None,
        offset: Optional[StrictInt] = None,
        limit: Optional[Annotated[int, Field(le=1000, strict=True)]] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get Data Asset View


        :param data_asset_id:
        :type data_asset_id: int
        :param acquisition_id:
        :type acquisition_id: int
        :param subject_id:
        :type subject_id: int
        :param subject_procedure_id:
        :type subject_procedure_id: int
        :param instrument_id:
        :type instrument_id: int
        :param data_asset_name:
        :type data_asset_name: str
        :param subject_name:
        :type subject_name: str
        :param instrument_name:
        :type instrument_name: str
        :param data_asset_location:
        :type data_asset_location: str
        :param offset:
        :type offset: int
        :param limit:
        :type limit: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_data_asset_view_serialize(
            data_asset_id=data_asset_id,
            acquisition_id=acquisition_id,
            subject_id=subject_id,
            subject_procedure_id=subject_procedure_id,
            instrument_id=instrument_id,
            data_asset_name=data_asset_name,
            subject_name=subject_name,
            instrument_name=instrument_name,
            data_asset_location=data_asset_location,
            offset=offset,
            limit=limit,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[DataAssetView]",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_data_asset_view_serialize(
        self,
        data_asset_id,
        acquisition_id,
        subject_id,
        subject_procedure_id,
        instrument_id,
        data_asset_name,
        subject_name,
        instrument_name,
        data_asset_location,
        offset,
        limit,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if data_asset_id is not None:
            
            _query_params.append(('data_asset_id', data_asset_id))
            
        if acquisition_id is not None:
            
            _query_params.append(('acquisition_id', acquisition_id))
            
        if subject_id is not None:
            
            _query_params.append(('subject_id', subject_id))
            
        if subject_procedure_id is not None:
            
            _query_params.append(('subject_procedure_id', subject_procedure_id))
            
        if instrument_id is not None:
            
            _query_params.append(('instrument_id', instrument_id))
            
        if data_asset_name is not None:
            
            _query_params.append(('data_asset_name', data_asset_name))
            
        if subject_name is not None:
            
            _query_params.append(('subject_name', subject_name))
            
        if instrument_name is not None:
            
            _query_params.append(('instrument_name', instrument_name))
            
        if data_asset_location is not None:
            
            _query_params.append(('data_asset_location', data_asset_location))
            
        if offset is not None:
            
            _query_params.append(('offset', offset))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/data_asset_view',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


