"""
    biodata-registry-service

     ## biodata-registry-service  Service to fetch data from Registry.  

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from datetime import datetime
from pydantic import Field, StrictInt, StrictStr
from typing import Optional
from typing_extensions import Annotated
from biodata_registry_api_client.models.data_asset_views_page import DataAssetViewsPage

from biodata_registry_api_client.api_client import ApiClient, RequestSerialized
from biodata_registry_api_client.api_response import ApiResponse
from biodata_registry_api_client.rest import RESTResponseType


class ViewsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_data_asset_view(
        self,
        next_token: Optional[StrictStr] = None,
        limit: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = None,
        created_at__gt: Optional[datetime] = None,
        created_at__lt: Optional[datetime] = None,
        created_at__gte: Optional[datetime] = None,
        created_at__lte: Optional[datetime] = None,
        updated_at__gt: Optional[datetime] = None,
        updated_at__lt: Optional[datetime] = None,
        updated_at__gte: Optional[datetime] = None,
        updated_at__lte: Optional[datetime] = None,
        data_asset_id: Optional[StrictInt] = None,
        acquisition_id: Optional[StrictInt] = None,
        instrument_id: Optional[StrictInt] = None,
        instrument_name__ilike: Optional[StrictStr] = None,
        data_asset_name__ilike: Optional[StrictStr] = None,
        data_asset_location__ilike: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> DataAssetViewsPage:
        """Get Data Asset View


        :param next_token:
        :type next_token: str
        :param limit:
        :type limit: int
        :param created_at__gt:
        :type created_at__gt: datetime
        :param created_at__lt:
        :type created_at__lt: datetime
        :param created_at__gte:
        :type created_at__gte: datetime
        :param created_at__lte:
        :type created_at__lte: datetime
        :param updated_at__gt:
        :type updated_at__gt: datetime
        :param updated_at__lt:
        :type updated_at__lt: datetime
        :param updated_at__gte:
        :type updated_at__gte: datetime
        :param updated_at__lte:
        :type updated_at__lte: datetime
        :param data_asset_id:
        :type data_asset_id: int
        :param acquisition_id:
        :type acquisition_id: int
        :param instrument_id:
        :type instrument_id: int
        :param instrument_name__ilike:
        :type instrument_name__ilike: str
        :param data_asset_name__ilike:
        :type data_asset_name__ilike: str
        :param data_asset_location__ilike:
        :type data_asset_location__ilike: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_data_asset_view_serialize(
            next_token=next_token,
            limit=limit,
            created_at__gt=created_at__gt,
            created_at__lt=created_at__lt,
            created_at__gte=created_at__gte,
            created_at__lte=created_at__lte,
            updated_at__gt=updated_at__gt,
            updated_at__lt=updated_at__lt,
            updated_at__gte=updated_at__gte,
            updated_at__lte=updated_at__lte,
            data_asset_id=data_asset_id,
            acquisition_id=acquisition_id,
            instrument_id=instrument_id,
            instrument_name__ilike=instrument_name__ilike,
            data_asset_name__ilike=data_asset_name__ilike,
            data_asset_location__ilike=data_asset_location__ilike,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "DataAssetViewsPage",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_data_asset_view_with_http_info(
        self,
        next_token: Optional[StrictStr] = None,
        limit: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = None,
        created_at__gt: Optional[datetime] = None,
        created_at__lt: Optional[datetime] = None,
        created_at__gte: Optional[datetime] = None,
        created_at__lte: Optional[datetime] = None,
        updated_at__gt: Optional[datetime] = None,
        updated_at__lt: Optional[datetime] = None,
        updated_at__gte: Optional[datetime] = None,
        updated_at__lte: Optional[datetime] = None,
        data_asset_id: Optional[StrictInt] = None,
        acquisition_id: Optional[StrictInt] = None,
        instrument_id: Optional[StrictInt] = None,
        instrument_name__ilike: Optional[StrictStr] = None,
        data_asset_name__ilike: Optional[StrictStr] = None,
        data_asset_location__ilike: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[DataAssetViewsPage]:
        """Get Data Asset View


        :param next_token:
        :type next_token: str
        :param limit:
        :type limit: int
        :param created_at__gt:
        :type created_at__gt: datetime
        :param created_at__lt:
        :type created_at__lt: datetime
        :param created_at__gte:
        :type created_at__gte: datetime
        :param created_at__lte:
        :type created_at__lte: datetime
        :param updated_at__gt:
        :type updated_at__gt: datetime
        :param updated_at__lt:
        :type updated_at__lt: datetime
        :param updated_at__gte:
        :type updated_at__gte: datetime
        :param updated_at__lte:
        :type updated_at__lte: datetime
        :param data_asset_id:
        :type data_asset_id: int
        :param acquisition_id:
        :type acquisition_id: int
        :param instrument_id:
        :type instrument_id: int
        :param instrument_name__ilike:
        :type instrument_name__ilike: str
        :param data_asset_name__ilike:
        :type data_asset_name__ilike: str
        :param data_asset_location__ilike:
        :type data_asset_location__ilike: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_data_asset_view_serialize(
            next_token=next_token,
            limit=limit,
            created_at__gt=created_at__gt,
            created_at__lt=created_at__lt,
            created_at__gte=created_at__gte,
            created_at__lte=created_at__lte,
            updated_at__gt=updated_at__gt,
            updated_at__lt=updated_at__lt,
            updated_at__gte=updated_at__gte,
            updated_at__lte=updated_at__lte,
            data_asset_id=data_asset_id,
            acquisition_id=acquisition_id,
            instrument_id=instrument_id,
            instrument_name__ilike=instrument_name__ilike,
            data_asset_name__ilike=data_asset_name__ilike,
            data_asset_location__ilike=data_asset_location__ilike,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "DataAssetViewsPage",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_data_asset_view_without_preload_content(
        self,
        next_token: Optional[StrictStr] = None,
        limit: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = None,
        created_at__gt: Optional[datetime] = None,
        created_at__lt: Optional[datetime] = None,
        created_at__gte: Optional[datetime] = None,
        created_at__lte: Optional[datetime] = None,
        updated_at__gt: Optional[datetime] = None,
        updated_at__lt: Optional[datetime] = None,
        updated_at__gte: Optional[datetime] = None,
        updated_at__lte: Optional[datetime] = None,
        data_asset_id: Optional[StrictInt] = None,
        acquisition_id: Optional[StrictInt] = None,
        instrument_id: Optional[StrictInt] = None,
        instrument_name__ilike: Optional[StrictStr] = None,
        data_asset_name__ilike: Optional[StrictStr] = None,
        data_asset_location__ilike: Optional[StrictStr] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get Data Asset View


        :param next_token:
        :type next_token: str
        :param limit:
        :type limit: int
        :param created_at__gt:
        :type created_at__gt: datetime
        :param created_at__lt:
        :type created_at__lt: datetime
        :param created_at__gte:
        :type created_at__gte: datetime
        :param created_at__lte:
        :type created_at__lte: datetime
        :param updated_at__gt:
        :type updated_at__gt: datetime
        :param updated_at__lt:
        :type updated_at__lt: datetime
        :param updated_at__gte:
        :type updated_at__gte: datetime
        :param updated_at__lte:
        :type updated_at__lte: datetime
        :param data_asset_id:
        :type data_asset_id: int
        :param acquisition_id:
        :type acquisition_id: int
        :param instrument_id:
        :type instrument_id: int
        :param instrument_name__ilike:
        :type instrument_name__ilike: str
        :param data_asset_name__ilike:
        :type data_asset_name__ilike: str
        :param data_asset_location__ilike:
        :type data_asset_location__ilike: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_data_asset_view_serialize(
            next_token=next_token,
            limit=limit,
            created_at__gt=created_at__gt,
            created_at__lt=created_at__lt,
            created_at__gte=created_at__gte,
            created_at__lte=created_at__lte,
            updated_at__gt=updated_at__gt,
            updated_at__lt=updated_at__lt,
            updated_at__gte=updated_at__gte,
            updated_at__lte=updated_at__lte,
            data_asset_id=data_asset_id,
            acquisition_id=acquisition_id,
            instrument_id=instrument_id,
            instrument_name__ilike=instrument_name__ilike,
            data_asset_name__ilike=data_asset_name__ilike,
            data_asset_location__ilike=data_asset_location__ilike,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "DataAssetViewsPage",
            '422': "HTTPValidationError",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_data_asset_view_serialize(
        self,
        next_token,
        limit,
        created_at__gt,
        created_at__lt,
        created_at__gte,
        created_at__lte,
        updated_at__gt,
        updated_at__lt,
        updated_at__gte,
        updated_at__lte,
        data_asset_id,
        acquisition_id,
        instrument_id,
        instrument_name__ilike,
        data_asset_name__ilike,
        data_asset_location__ilike,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if next_token is not None:
            
            _query_params.append(('next_token', next_token))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        if created_at__gt is not None:
            if isinstance(created_at__gt, datetime):
                _query_params.append(
                    (
                        'created_at__gt',
                        created_at__gt.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('created_at__gt', created_at__gt))
            
        if created_at__lt is not None:
            if isinstance(created_at__lt, datetime):
                _query_params.append(
                    (
                        'created_at__lt',
                        created_at__lt.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('created_at__lt', created_at__lt))
            
        if created_at__gte is not None:
            if isinstance(created_at__gte, datetime):
                _query_params.append(
                    (
                        'created_at__gte',
                        created_at__gte.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('created_at__gte', created_at__gte))
            
        if created_at__lte is not None:
            if isinstance(created_at__lte, datetime):
                _query_params.append(
                    (
                        'created_at__lte',
                        created_at__lte.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('created_at__lte', created_at__lte))
            
        if updated_at__gt is not None:
            if isinstance(updated_at__gt, datetime):
                _query_params.append(
                    (
                        'updated_at__gt',
                        updated_at__gt.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('updated_at__gt', updated_at__gt))
            
        if updated_at__lt is not None:
            if isinstance(updated_at__lt, datetime):
                _query_params.append(
                    (
                        'updated_at__lt',
                        updated_at__lt.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('updated_at__lt', updated_at__lt))
            
        if updated_at__gte is not None:
            if isinstance(updated_at__gte, datetime):
                _query_params.append(
                    (
                        'updated_at__gte',
                        updated_at__gte.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('updated_at__gte', updated_at__gte))
            
        if updated_at__lte is not None:
            if isinstance(updated_at__lte, datetime):
                _query_params.append(
                    (
                        'updated_at__lte',
                        updated_at__lte.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('updated_at__lte', updated_at__lte))
            
        if data_asset_id is not None:
            
            _query_params.append(('data_asset_id', data_asset_id))
            
        if acquisition_id is not None:
            
            _query_params.append(('acquisition_id', acquisition_id))
            
        if instrument_id is not None:
            
            _query_params.append(('instrument_id', instrument_id))
            
        if instrument_name__ilike is not None:
            
            _query_params.append(('instrument_name__ilike', instrument_name__ilike))
            
        if data_asset_name__ilike is not None:
            
            _query_params.append(('data_asset_name__ilike', data_asset_name__ilike))
            
        if data_asset_location__ilike is not None:
            
            _query_params.append(('data_asset_location__ilike', data_asset_location__ilike))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/data_asset_view',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


