# coding: utf-8

"""
    biodata-registry-service

     ## biodata-registry-service  Service to fetch data from Registry.  

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DataAssetView(BaseModel):
    """
    DataAssetView
    """ # noqa: E501
    data_asset_id: Optional[StrictInt] = None
    acquisition_id: Optional[StrictInt] = None
    subject_id: Optional[StrictInt] = None
    acquisition_data: Optional[Dict[str, Any]] = None
    processes_data: Optional[List[Optional[Dict[str, Any]]]]
    instrument_data: Optional[List[Dict[str, Any]]]
    data_asset_location: Optional[Annotated[str, Field(strict=True, max_length=254)]] = None
    data_asset_name: Optional[Annotated[str, Field(strict=True, max_length=254)]] = None
    data_asset_data: Optional[Dict[str, Any]] = None
    data_asset_external_links: Optional[Dict[str, Any]] = None
    subject_name: Optional[Annotated[str, Field(strict=True, max_length=254)]] = None
    subject_data: Optional[Dict[str, Any]] = None
    subject_procedures_data: Optional[List[Dict[str, Any]]]
    quality_control_data: Optional[List[Dict[str, Any]]]
    __properties: ClassVar[List[str]] = ["data_asset_id", "acquisition_id", "subject_id", "acquisition_data", "processes_data", "instrument_data", "data_asset_location", "data_asset_name", "data_asset_data", "data_asset_external_links", "subject_name", "subject_data", "subject_procedures_data", "quality_control_data"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DataAssetView from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if data_asset_id (nullable) is None
        # and model_fields_set contains the field
        if self.data_asset_id is None and "data_asset_id" in self.model_fields_set:
            _dict['data_asset_id'] = None

        # set to None if acquisition_id (nullable) is None
        # and model_fields_set contains the field
        if self.acquisition_id is None and "acquisition_id" in self.model_fields_set:
            _dict['acquisition_id'] = None

        # set to None if subject_id (nullable) is None
        # and model_fields_set contains the field
        if self.subject_id is None and "subject_id" in self.model_fields_set:
            _dict['subject_id'] = None

        # set to None if processes_data (nullable) is None
        # and model_fields_set contains the field
        if self.processes_data is None and "processes_data" in self.model_fields_set:
            _dict['processes_data'] = None

        # set to None if instrument_data (nullable) is None
        # and model_fields_set contains the field
        if self.instrument_data is None and "instrument_data" in self.model_fields_set:
            _dict['instrument_data'] = None

        # set to None if data_asset_location (nullable) is None
        # and model_fields_set contains the field
        if self.data_asset_location is None and "data_asset_location" in self.model_fields_set:
            _dict['data_asset_location'] = None

        # set to None if data_asset_name (nullable) is None
        # and model_fields_set contains the field
        if self.data_asset_name is None and "data_asset_name" in self.model_fields_set:
            _dict['data_asset_name'] = None

        # set to None if subject_name (nullable) is None
        # and model_fields_set contains the field
        if self.subject_name is None and "subject_name" in self.model_fields_set:
            _dict['subject_name'] = None

        # set to None if subject_procedures_data (nullable) is None
        # and model_fields_set contains the field
        if self.subject_procedures_data is None and "subject_procedures_data" in self.model_fields_set:
            _dict['subject_procedures_data'] = None

        # set to None if quality_control_data (nullable) is None
        # and model_fields_set contains the field
        if self.quality_control_data is None and "quality_control_data" in self.model_fields_set:
            _dict['quality_control_data'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DataAssetView from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "data_asset_id": obj.get("data_asset_id"),
            "acquisition_id": obj.get("acquisition_id"),
            "subject_id": obj.get("subject_id"),
            "acquisition_data": obj.get("acquisition_data"),
            "processes_data": obj.get("processes_data"),
            "instrument_data": obj.get("instrument_data"),
            "data_asset_location": obj.get("data_asset_location"),
            "data_asset_name": obj.get("data_asset_name"),
            "data_asset_data": obj.get("data_asset_data"),
            "data_asset_external_links": obj.get("data_asset_external_links"),
            "subject_name": obj.get("subject_name"),
            "subject_data": obj.get("subject_data"),
            "subject_procedures_data": obj.get("subject_procedures_data"),
            "quality_control_data": obj.get("quality_control_data")
        })
        return _obj


